name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}

      - name: Install Dependency
        run: npm install

      - name: Build Library
        run: npm run buildonline && npm run buildlibrary

      - name: Make offline cache
        run: npx workbox injectManifest workbox-config.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist